export const FETCH_SEARCH_DATA_START = "FETCH_SEARCH_DATA_START";
export const FETCH_SEARCH_DATA_SUCCESS = "FETCH_SEARCH_DATA_SUCCESS";
export const FETCH_SEARCH_DATA_FAIL = "FETCH_SEARCH_DATA_FAIL";

export const SET_SEARCH_TOTAL_PAGES = 'SET_SEARCH_TOTAL_PAGES';
export const SET_SEARCH_CURRENT_PAGE = 'SET_SEARCH_CURRENT_PAGE';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_LAST_SEARCH = 'SET_LAST_SEARCH';
