export const FETCH_PEOPLE_CARD_DATA_START = "FETCH_PEOPLE_CARD_DATA_START";
export const FETCH_PEOPLE_CARD_DATA_SUCCESS = "FETCH_PEOPLE_CARD_DATA_SUCCESS";
export const FETCH_PEOPLE_CARD_DATA_FAIL = "FETCH_PEOPLE_CARD_DATA_FAIL";
export const CLEANUP_CARD_DATA = 'CLEANUP_CARD_DATA';

export const FETCH_PEOPLE_CREDITS_START = "FETCH_PEOPLE_CREDITS_START";
export const FETCH_PEOPLE_CREDITS_CREW_SUCCESS = "FETCH_PEOPLE_CREDITS_CREW_SUCCESS";
export const FETCH_PEOPLE_CREDITS_CAST_SUCCESS = "FETCH_PEOPLE_CREDITS_CAST_SUCCESS";
export const FETCH_PEOPLE_CREDITS_FAIL = "FETCH_PEOPLE_CREDITS_FAIL";
// export const CLEANUP_CARD_DATA = 'CLEANUP_CARD_DATA';
