export const FETCH_POPULAR_MOVIES_START = "FETCH_POPULAR_MOVIES_START";
export const FETCH_POPULAR_MOVIES_SUCCESS = "FETCH_POPULAR_MOVIES_SUCCESS";
export const FETCH_POPULAR_MOVIES_FAIL = "FETCH_POPULAR_MOVIES_FAIL";
export const SET_MOVIES_TOTAL_PAGES = "SET_MOVIES_TOTAL_PAGES";
export const SET_MOVIES_CURRENT_PAGE = "SET_MOVIES_CURRENT_PAGE";
export const CLEANUP_POPULAR_MOVIES = "CLEANUP_POPULAR_MOVIES";
export const CLEANUP_POPULAR_MOVIES_CURRENT_PAGE = "CLEANUP_POPULAR_MOVIES_CURRENT_PAGE";
export const FETCH_ALL_POPULAR_MOVIES_START = "FETCH_ALL_POPULAR_MOVIES_START";
export const FETCH_ALL_POPULAR_MOVIES_SUCCESS = "FETCH_ALL_POPULAR_MOVIES_SUCCESS";
export const FETCH_ALL_POPULAR_MOVIES_FAIL = "FETCH_ALL_POPULAR_MOVIES_FAIL";

export const FETCH_POPULAR_TVS_START = "FETCH_POPULAR_TVS_START";
export const FETCH_POPULAR_TVS_SUCCESS = "FETCH_POPULAR_TVS_SUCCESS";
export const FETCH_POPULAR_TVS_FAIL = "FETCH_POPULAR_TVS_FAIL";
export const SET_TVS_TOTAL_PAGES = "SET_TVS_TOTAL_PAGES";
export const SET_TVS_CURRENT_PAGE = "SET_TVS_CURRENT_PAGE";
export const CLEANUP_POPULAR_TVS_CURRENT_PAGE = "CLEANUP_POPULAR_TVS_CURRENT_PAGE";

export const FETCH_TRANDING_PER_DAY_START = "FETCH_TRANDING_PER_DAY_START";
export const FETCH_TRANDING_PER_DAY_SUCCESS = "FETCH_TRANDING_PER_DAY_SUCCESS";
export const FETCH_TRANDING_PER_DAY_FAIL = "FETCH_TRANDING_PER_DAY_FAIL";
export const FETCH_TRANDING_PER_WEEK_START = "FETCH_TRANDING_PER_WEEK_START";
export const FETCH_TRANDING_PER_WEEK_SUCCESS =
  "FETCH_TRANDING_PER_WEEK_SUCCESS";
export const FETCH_TRANDING_PER_WEEK_FAIL = "FETCH_TRANDING_PER_WEEK_FAIL";

export const FETCH_NOW_PLAYING_MOVIES_START = "FETCH_NOW_PLAYING_MOVIES_START";
export const FETCH_NOW_PLAYING_MOVIES_SUCCESS =
  "FETCH_NOW_PLAYING_MOVIES_SUCCESS";
export const FETCH_NOW_PLAYING_MOVIES_FAIL = "FETCH_NOW_PLAYING_MOVIES_FAIL";

export const FETCH_LATEST_TV_START = "FETCH_LATEST_TV_START";
export const FETCH_LATEST_TV_SUCCESS = "FETCH_LATEST_TV_SUCCESS";
export const FETCH_LATEST_TV_FAIL = "FETCH_LATEST_TV_FAIL";

export const FETCH_CARD_DATA_START = "FETCH_CARD_DATA_START";
export const FETCH_CARD_DATA_SUCCESS = "FETCH_CARD_DATA_SUCCESS";
export const FETCH_CARD_DATA_FAIL = "FETCH_CARD_DATA_FAIL";
export const CLEANUP_CARD_DATA = "CLEANUP_CARD_DATA";

export const FETCH_TRAILERS_START = "FETCH_TRAILERS_START";
export const FETCH_TRAILERS_SUCCESS = "FETCH_TRAILERS_SUCCESS";
export const FETCH_TRAILERS_FAIL = "FETCH_TRAILERS_FAIL";

export const FETCH_CREW_AND_CAST_START = "FETCH_CREW_AND_CAST_START";
export const FETCH_CREW_SUCCESS = "FETCH_CREW_SUCCESS";
export const FETCH_CAST_SUCCESS = "FETCH_CAST_SUCCESS";
export const SET_TOP_CAST_SUCCESS = "SET_TOP_CAST_SUCCESS";
export const FETCH_CREW_AND_CAST_FAIL = "FETCH_CREW_AND_CAST_FAIL";
export const CLEANUP_TOP_CAST = "CLEANUP_TOP_CAST";

export const FETCH_RECOMMEND_AND_SIMILAR_START =
  "FETCH_RECOMMEND_AND_SIMILAR_START";
export const FETCH_RECOMMEND_SUCCESS = "FETCH_RECOMMEND_SUCCESS";
export const FETCH_SIMILAR_SUCCESS = "FETCH_SIMILAR_SUCCESS";
export const FETCH_RECOMMEND_AND_SIMILAR_FAIL =
  "FETCH_RECOMMEND_AND_SIMILAR_FAIL";
